Bring in Neon setcap changes

diff --git a/debian/kwin-wayland.postinst b/debian/kwin-wayland.postinst
--- a/debian/kwin-wayland.postinst
+++ b/debian/kwin-wayland.postinst
@@ -3,17 +3,25 @@
 set -e
 
 if [ "$1" = configure ]; then
-    # Set the capabilities
-    if command -v setcap > /dev/null && \
-       setcap "CAP_SYS_RESOURCE=+ep" \
-            /usr/bin/kwin_wayland; then
-        echo "Sucessfully setting capabilities for kwin_wayland"
+    # Try to setcap or fall back to setuid.
+    # The specific setcap invocations also need to be whitelisted to make the
+    # build pass (in debian/meta/setcap.yaml as a nested array of argument
+    # arrays).
+    if command -v setcap > /dev/null; then
+        cap="CAP_SYS_NICE=+ep"
+        path="/usr/bin/kwin_wayland"
+        if setcap $cap $path; then
+            echo "Setcap worked for $path!"
+        else
+            echo "Setcap failed for $path, falling back to setuid" >&2
+            chmod u+s $path
+        fi
     else
-        echo "Failed to set capabilities for kwin_wayland" >&2
+        echo "Setcap is not installed, falling back to setuid for $path" >&2
+        chmod u+s $path
     fi
 fi
 
 #DEBHELPER#
 
 exit 0
-
